name: Tests
on:
  pull_request:
    branches: ["master"]
jobs:
  Install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create lock file
        run: touch package-lock.json

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install
        run: npm install

      - name: Format
        run: npm run format:write

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
